# Internal status logger level
status = ERROR
name = Log4j2PropertiesConfig

# List of Appenders
appenders = console

# Console Appender Definition
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# Root Logger Configuration
rootLogger.level = WARN
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT

# Application Logger for 'sbdl'
logger.sbdl.name = sbdl
logger.sbdl.level = INFO
logger.sbdl.additivity = false
logger.sbdl.appenderRefs = stdout
logger.sbdl.appenderRef.stdout.ref = STDOUT

# Suppress noisy Spark & Parquet logs
logger.sparkRepl.name = org.apache.spark.repl.Main
logger.sparkRepl.level = WARN

logger.jetty.name = org.spark_project.jetty
logger.jetty.level = WARN

logger.parquet.name = org.apache.parquet
logger.parquet.level = ERROR

logger.hadoopHive.name = org.apache.hadoop.hive.metastore.RetryingHMSHandler
logger.hadoopHive.level = FATAL