[LOCAL]
enable.hive = false
hive.database = null
account.filter = active_ind = 1
party.filter =
address.filter =
kafka.bootstrap.servers = kafka-30f74b87-hexum03-c3c3.d.aivencloud.com:16565
kafka.topic = sbdl-kafka-cloud
kafka.ssl.truststore.type = PEM
kafka.security.protocol = SASL_SSL
kafka.sasl.mechanism = SCRAM-SHA-256
kafka.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username='{}' password='{}';
[QA]
enable.hive = true
hive.database = sbdl_db_qa
kafka.topic = sbdl_kafka_qa
[PROD]
enable.hive = true
hive.database = sbdl_db
kafka.topic = sbdl_kafka

    